import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const errs = [];
page.on('pageerror', (e) => errs.push('PAGE: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push('CE: ' + m.text().slice(0, 200)); });
await page.goto('http://127.0.0.1:5199/g005-radiology-ris/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.setItem('ris_current_user', JSON.stringify({ id: 'A001', name: '管理员', role: '管理员', department: '信息科' })));
await page.goto('http://127.0.0.1:5199/g005-radiology-ris/review-center', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(3000);
console.log('Errors:');
for (const e of errs.slice(0, 5)) console.log('  ' + e.slice(0, 200));
await browser.close();