// 彻底修复 - 把所有中文测试名替换为拼音
const fs = require('fs');
const f = 'E:/opencode work/FS/G005-RISv-3.0.0/test-v40-e2e.mjs';
let c = fs.readFileSync(f, 'utf8');
const map = {
  '系统管理�?': 'SysAdmin',
  '管理�?': 'Admin',
  '信息�?': 'IT',
  '总数': 'Total',
  '预设': 'Presets',
  '保存': 'Save',
  '导出': 'Export',
  '术语': 'Terms',
  '词': 'Words',
  '提取': 'Extract',
  '诊断': 'Diagnosis',
  '项': 'Items',
  '字': 'Chars',
  '常数': 'Constants',
  '计算': 'Calc',
  '规划': 'Plan',
  '轴位': 'Axis',
  '预测': 'Predict',
  'SE=': 'SE=',
  '同视机': 'Synop',
  'Pentacam': 'Pentacam',
  'Kmax=': 'Kmax=',
  '试戴': 'Fitting',
  '处方': 'Rx',
  '分级': 'Grade',
  '模型': 'Model',
  '生物标志物': 'Biomarker',
  'AI QC': 'AI_QC',
  '规则': 'Rules',
  '条': 'Items',
  'DICOM MWL 重扫': 'DICOM_MWL',
  'Late Fusion': 'LateFusion',
  'dr=': 'dr=',
  'Cross-Modal Attention': 'CrossModalAttn',
  '路权重': 'Paths',
  'SHAP 解释': 'SHAP',
  '因素': 'Factors',
  '多模态配准': 'MultimReg',
  'RMSE=': 'RMSE=',
  'Real DICOM Viewer': 'RealDicomViewer',
  'AI 报告书写': 'AIReportWriter',
  'Toric 规划': 'ToricPlanner',
  '斜视': 'Strabismus',
  '神经眼科': 'NeuroOph',
  '眼眶': 'Oncology',
  '角膜': 'Cornea',
  '接触镜': 'ContactLens',
  '低视力': 'LowVision',
  'PR1': 'PR1',
  'PR2': 'PR2',
  'PR3': 'PR3',
  'PR4': 'PR4',
  'PR5': 'PR5',
  'PR6': 'PR6',
  'PR7': 'PR7',
};
for (const [k, v] of Object.entries(map)) {
  c = c.replace(new RegExp(k, 'g'), v);
}
fs.writeFileSync(f, c, 'utf8');
console.log('All Chinese replaced');
