import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const USER = JSON.stringify({ id: 'A001', name: '系统管理员', role: '管理员', department: '信息科' });
const errors = [];
page.on('pageerror', (e) => errors.push({ type: 'pageerror', msg: e.message }));
page.on('console', (m) => { if (m.type() === 'error') errors.push({ type: 'cerr', msg: m.text() }); });
await page.goto('http://127.0.0.1:5199/g005-radiology-ris/', { waitUntil: 'networkidle' });
await page.evaluate((u) => localStorage.setItem('ris_current_user', u), USER);
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
console.log('Errors:', errors.length);
errors.slice(0, 10).forEach(e => console.log(e.type, ':', e.msg.slice(0, 200)));
await browser.close();
