import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const USER = JSON.stringify({ id: 'A001', name: '系统管理员', role: '管理员', department: '信息科' });
page.on('pageerror', (e) => console.log('[err]', e.message));
page.on('console', (m) => { if (m.type() === 'error') console.log('[cerr]', m.text().slice(0, 200)); });
await page.goto('http://127.0.0.1:5199/g005-radiology-ris/', { waitUntil: 'networkidle' });
await page.evaluate((u) => localStorage.setItem('ris_current_user', u), USER);
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
const links = await page.$$eval('aside a', (els) => els.length);
console.log('Total sidebar links:', links);
const html = await page.content();
console.log('HTML length:', html.length);
console.log('Has 剂量追踪:', html.includes('剂量追踪'));
console.log('Has 设备物资:', html.includes('设备物资'));
await browser.close();