import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
p.on('pageerror', e => console.log('PE:', e.message.slice(0, 200)));
await p.goto('http://127.0.0.1:5199/g005-radiology-ris/');
await p.evaluate(() => localStorage.setItem('ris_current_user', JSON.stringify({id:'A001',name:'系统管理员',role:'管理员',department:'信息科'})));
await p.goto('http://127.0.0.1:5199/g005-radiology-ris/consultation');
await p.waitForTimeout(3500);
await p.screenshot({ path: 'verify-consult.png', fullPage: false });
const hasEB = await p.evaluate(() => document.body.innerText.includes('ErrorBoundary caught'));
const hasNaN = await p.evaluate(() => /NaN[%°)]/.test(document.body.innerText));
const bodyText = await p.evaluate(() => document.body.innerText.slice(0, 500));
console.log('ErrorBoundary:', hasEB);
console.log('NaN:', hasNaN);
console.log('Body sample:', bodyText);
await p.goto('http://127.0.0.1:5199/g005-radiology-ris/dicom-viewer');
await p.waitForTimeout(3000);
const dicomHasEB = await p.evaluate(() => document.body.innerText.includes('ErrorBoundary caught'));
console.log('DicomViewer ErrorBoundary:', dicomHasEB);
await p.screenshot({ path: 'verify-dicom.png', fullPage: false });
await b.close();
