/**
 * G005 放射RIS系统 v3.0.1 - 路由表
 * 从 v3.0.0 单体 App.tsx 拆出,所有 84 个 lazy 页面 + 1 个 Navigate 重定向
 */
import React, { lazy } from 'react'
import { Navigate, type RouteObject } from 'react-router-dom'

const HomePage = lazy(() => import('../pages/HomePage'))
const PatientPage = lazy(() => import('../pages/PatientPage'))
const ExamPage = lazy(() => import('../pages/ExamPage'))
const ReportPage = lazy(() => import('../pages/ReportPage'))
const WorklistPage = lazy(() => import('../pages/WorklistPage'))
const StatisticsPage = lazy(() => import('../pages/StatisticsPage'))
const CriticalValuePage = lazy(() => import('../pages/CriticalValuePage'))
const TermLibraryPage = lazy(() => import('../pages/TermLibraryPage'))
const DevicePage = lazy(() => import('../pages/DevicePage'))
const ConsultationPage = lazy(() => import('../pages/ConsultationPage'))
const QCPage = lazy(() => import('../pages/QCPage'))
const AppointmentPage = lazy(() => import('../pages/AppointmentPage'))
const DoseTrackPage = lazy(() => import('../pages/DoseTrackPage'))
const QueueCallPage = lazy(() => import('../pages/QueueCallPage'))
const DicomViewerPage = lazy(() => import('../pages/DicomViewerPage'))
const TypicalCasesPage = lazy(() => import('../pages/TypicalCasesPage'))
const FindingLibraryPage = lazy(() => import('../pages/FindingLibraryPage'))
const OperationLogPage = lazy(() => import('../pages/OperationLogPage'))
const NotificationCenter = lazy(() => import('../pages/NotificationCenter'))
const SchedulePage = lazy(() => import('../pages/SchedulePage'))
const DepartmentPage = lazy(() => import('../pages/DepartmentPage'))
const MaterialsPage = lazy(() => import('../pages/MaterialsPage'))
const PrintManagementPage = lazy(() => import('../pages/PrintManagementPage'))
const RegionalReportPage = lazy(() => import('../pages/RegionalReportPage'))
const AIAssistPage = lazy(() => import('../pages/AIAssistPage'))
const CostAnalysisPage = lazy(() => import('../pages/CostAnalysisPage'))
const EquipmentLifecyclePage = lazy(() => import('../pages/EquipmentLifecyclePage'))
const FollowUpPage = lazy(() => import('../pages/FollowUpPage'))
const CancerScreenPage = lazy(() => import('../pages/CancerScreenPage'))
const NationalReportPage = lazy(() => import('../pages/NationalReportPage'))
const InsuranceAuditPage = lazy(() => import('../pages/InsuranceAuditPage'))
const DataReportCenterPage = lazy(() => import('../pages/DataReportCenterPage'))
const DictionaryPage = lazy(() => import('../pages/DictionaryPage'))
const OperationsCenterPage = lazy(() => import('../pages/OperationsCenterPage'))
const DepartmentDashboardPage = lazy(() => import('../pages/DepartmentDashboardPage'))
const StatsReportPage = lazy(() => import('../pages/StatsReportPage'))
const ClinicalDataPage = lazy(() => import('../pages/ClinicalDataPage'))
const TemplateManagementPage = lazy(() => import('../pages/TemplateManagementPage'))
const TemplateDesignerPage = lazy(() => import('../pages/TemplateDesignerPage'))
const TemplateInheritancePage = lazy(() => import('../pages/TemplateInheritancePage'))
const TemplateCategoryPage = lazy(() => import('../pages/TemplateCategoryPage'))
const ReportReviewPage = lazy(() => import('../pages/ReportReviewPage'))
const ReportRevisionsPage = lazy(() => import('../pages/ReportRevisionsPage'))
const CollaborationPage = lazy(() => import('../pages/CollaborationPage'))
const KeywordCheckPage = lazy(() => import('../pages/KeywordCheckPage'))
const ReportScoreRulePage = lazy(() => import('../pages/ReportScoreRulePage'))
const ReportDefectLibraryPage = lazy(() => import('../pages/ReportDefectLibraryPage'))
const AIReportDraftPage = lazy(() => import('../pages/AIReportDraftPage'))
const CriticalValueRulePage = lazy(() => import('../pages/CriticalValueRulePage'))
const CriticalValueStatsPage = lazy(() => import('../pages/CriticalValueStatsPage'))
const SpecialAssessmentPages = lazy(() => import('../pages/SpecialAssessmentPages'))
const ReportExportPage = lazy(() => import('../pages/ReportExportPage'))
const ReportDeliveryPage = lazy(() => import('../pages/ReportDeliveryPage'))
const PublishPage = lazy(() => import('../pages/PublishPage'))
const PatientReportPortalPage = lazy(() => import('../pages/PatientReportPortalPage'))
const CASignaturePage = lazy(() => import('../pages/CASignaturePage'))
const BlockchainProofPage = lazy(() => import('../pages/BlockchainProofPage'))
const AppointmentManagementPage = lazy(() => import('../pages/AppointmentManagementPage'))
const DeviceFaultPage = lazy(() => import('../pages/DeviceFaultPage'))
const AIQCPage = lazy(() => import('../pages/AIQCPage'))
const AIStructuredReportPage = lazy(() => import('../pages/AIStructuredReportPage'))
const RegionalImagingPage = lazy(() => import('../pages/RegionalImagingPage'))
const EquipmentEfficiencyPage = lazy(() => import('../pages/EquipmentEfficiencyPage'))
const UserManagementPage = lazy(() => import('../pages/UserManagementPage'))
const PatientPortalPage = lazy(() => import('../pages/PatientPortalPage'))
const DirectorDashboardPage = lazy(() => import('../pages/DirectorDashboardPage'))
const GreenITPage = lazy(() => import('../pages/GreenITPage'))
const ResearchPage = lazy(() => import('../pages/ResearchPage'))
const DicomPrintPage = lazy(() => import('../pages/System/DicomPrintPage'))
const NuclearStatsPage = lazy(() => import('../pages/NuclearStatsPage'))
const AIMedicalDevicePage = lazy(() => import('../pages/AIMedicalDevicePage'))
const TermSynonymGraphPage = lazy(() => import('../pages/TermSynonymGraphPage'))
const ReportPhraseBankPage = lazy(() => import('../pages/ReportPhraseBankPage'))
const ReportKpiDashboardPage = lazy(() => import('../pages/ReportKpiDashboardPage'))
const DoctorWorkloadPage = lazy(() => import('../pages/DoctorWorkloadPage'))
const DiagnosisAccuracyPage = lazy(() => import('../pages/DiagnosisAccuracyPage'))
const ReportTimelinessPage = lazy(() => import('../pages/ReportTimelinessPage'))
const ReportSearchPage = lazy(() => import('../pages/ReportSearchPage'))
const ChargeItemPage = lazy(() => import('../pages/rcm/ChargeItemPage'))
const AccountsReceivablePage = lazy(() => import('../pages/rcm/AccountsReceivablePage'))
const RevenueAnalysisPage = lazy(() => import('../pages/rcm/RevenueAnalysisPage'))
const CostAccountingPage = lazy(() => import('../pages/rcm/CostAccountingPage'))
const FinancialReportsPage = lazy(() => import('../pages/rcm/FinancialReportsPage'))
const BusinessContinuityPage = lazy(() => import('../pages/BusinessContinuityPage'))
const CloudStorageDashboardPage = lazy(() => import('../pages/CloudStorageDashboardPage'))
const EnterpriseSearchPage = lazy(() => import('../pages/EnterpriseSearchPage'))
const MultiSiteDashboardPage = lazy(() => import('../pages/MultiSiteDashboardPage'))
const VNADashboardPage = lazy(() => import('../pages/VNADashboardPage'))
const AdverseEventPage = lazy(() => import('../pages/safety/AdverseEventPage'))
const CQIPage = lazy(() => import('../pages/safety/CQIPage'))
const PatientSafetyGoalsPage = lazy(() => import('../pages/safety/PatientSafetyGoalsPage'))
const RadiationSafetyPage = lazy(() => import('../pages/safety/RadiationSafetyPage'))
const RCAAnalysisPage = lazy(() => import('../pages/safety/RCAAnalysisPage'))
const RiskManagementPage = lazy(() => import('../pages/safety/RiskManagementPage'))
const AdverseReactionPage = lazy(() => import('../pages/contrast/AdverseReactionPage'))
const ContrastInjectionWorkstationPage = lazy(() => import('../pages/contrast/ContrastInjectionWorkstationPage'))
const ContrastInventoryPage = lazy(() => import('../pages/contrast/ContrastInventoryPage'))
const ContrastQualityCompliancePage = lazy(() => import('../pages/contrast/ContrastQualityCompliancePage'))
const CvDatabasePage = lazy(() => import('../pages/cardiac/CvDatabasePage'))
const CvOperationsPage = lazy(() => import('../pages/cardiac/CvOperationsPage'))
const CvQcPage = lazy(() => import('../pages/cardiac/CvQcPage'))
const DeviceOpsPage = lazy(() => import('../pages/ops/DeviceOpsPage'))
const HrOperationsPage = lazy(() => import('../pages/ops/HrOperationsPage'))
const OpsDashboardPage = lazy(() => import('../pages/ops/OpsDashboardPage'))
const CdsManagementPage = lazy(() => import('../pages/cds/CdsManagementPage'))
const CdsStatisticsPage = lazy(() => import('../pages/cds/CdsStatisticsPage'))
const DepartmentFinancePage = lazy(() => import('../pages/finance/DepartmentFinancePage'))
const PatientFinancePage = lazy(() => import('../pages/finance/PatientFinancePage'))
const DepartmentOperationsPage = lazy(() => import('../pages/mammo/DepartmentOperationsPage'))
const QualityManagementPage = lazy(() => import('../pages/mammo/QualityManagementPage'))
const SelfServicePortal = lazy(() => import('../pages/patient/SelfServicePortal'))
const ServiceManagement = lazy(() => import('../pages/patient/ServiceManagement'))
const PatientEducationPage = lazy(() => import('../pages/education/PatientEducationPage'))
const MedicalAlliancePage = lazy(() => import('../pages/hie/MedicalAlliancePage'))
const KioskCheckIn = lazy(() => import('../pages/kiosk/KioskCheckIn'))
const PatientMobileApp = lazy(() => import('../pages/mobile/PatientMobileApp'))
const DoctorMobileWorkstation = lazy(() => import('../pages/mobile/doctor/DoctorMobileWorkstation'))
const NurseMobileWorkstation = lazy(() => import('../pages/mobile/nurse/NurseMobileWorkstation'))
const TechMobileWorkstation = lazy(() => import('../pages/mobile/tech/TechMobileWorkstation'))
const DepartmentQualityPage = lazy(() => import('../pages/quality/DepartmentQualityPage'))

export const routes: RouteObject[] = [
  { path: '/', element: React.createElement(HomePage) },
  { path: '/worklist', element: React.createElement(WorklistPage) },
  { path: '/patients', element: React.createElement(PatientPage) },
  { path: '/patient/:id', element: React.createElement(PatientPage) },
  { path: '/exams', element: React.createElement(ExamPage) },
  { path: '/reports', element: React.createElement(ReportPage) },
  { path: '/statistics', element: React.createElement(StatisticsPage) },
  { path: '/critical-value', element: React.createElement(CriticalValuePage) },
  { path: '/term-library', element: React.createElement(TermLibraryPage) },
  { path: '/devices', element: React.createElement(DevicePage) },
  { path: '/consultation', element: React.createElement(ConsultationPage) },
  { path: '/qc', element: React.createElement(QCPage) },
  { path: '/appointments', element: React.createElement(AppointmentPage) },
  { path: '/dose-track', element: React.createElement(DoseTrackPage) },
  { path: '/queue-call', element: React.createElement(QueueCallPage) },
  { path: '/dicom-viewer', element: React.createElement(DicomViewerPage) },
  { path: '/typical-cases', element: React.createElement(TypicalCasesPage) },
  { path: '/finding-library', element: React.createElement(FindingLibraryPage) },
  { path: '/operation-log', element: React.createElement(OperationLogPage) },
  { path: '/notification-center', element: React.createElement(NotificationCenter) },
  { path: '/schedule', element: React.createElement(SchedulePage) },
  { path: '/department', element: React.createElement(DepartmentPage) },
  { path: '/materials', element: React.createElement(MaterialsPage) },
  { path: '/print-management', element: React.createElement(PrintManagementPage) },
  { path: '/regional-report', element: React.createElement(RegionalReportPage) },
  { path: '/ai-assist', element: React.createElement(AIAssistPage) },
  { path: '/cost-analysis', element: React.createElement(CostAnalysisPage) },
  { path: '/equipment-lifecycle', element: React.createElement(EquipmentLifecyclePage) },
  { path: '/follow-up', element: React.createElement(FollowUpPage) },
  { path: '/cancer-screen', element: React.createElement(CancerScreenPage) },
  { path: '/national-report', element: React.createElement(NationalReportPage) },
  { path: '/insurance-audit', element: React.createElement(InsuranceAuditPage) },
  { path: '/data-report-center', element: React.createElement(DataReportCenterPage) },
  { path: '/dictionary', element: React.createElement(DictionaryPage) },
  { path: '/operations-center', element: React.createElement(OperationsCenterPage) },
  { path: '/department-dashboard', element: React.createElement(DepartmentDashboardPage) },
  { path: '/stats-report', element: React.createElement(StatsReportPage) },
  { path: '/clinical-data', element: React.createElement(ClinicalDataPage) },
  { path: '/template-management', element: React.createElement(TemplateManagementPage) },
  { path: '/template-designer', element: React.createElement(TemplateDesignerPage) },
  { path: '/template-designer/:id', element: React.createElement(TemplateDesignerPage) },
  { path: '/template-inheritance', element: React.createElement(TemplateInheritancePage) },
  { path: '/template-category', element: React.createElement(TemplateCategoryPage) },
  { path: '/report-review', element: React.createElement(ReportReviewPage) },
  { path: '/report-revisions', element: React.createElement(ReportRevisionsPage) },
  { path: '/collaboration', element: React.createElement(CollaborationPage) },
  { path: '/keyword-check', element: React.createElement(KeywordCheckPage) },
  { path: '/report-score-rule', element: React.createElement(ReportScoreRulePage) },
  { path: '/report-defect-library', element: React.createElement(ReportDefectLibraryPage) },
  { path: '/ai-report-draft', element: React.createElement(AIReportDraftPage) },
  { path: '/critical-value-rule', element: React.createElement(CriticalValueRulePage) },
  { path: '/critical-value-stats', element: React.createElement(CriticalValueStatsPage) },
  { path: '/special-assessment', element: React.createElement(SpecialAssessmentPages) },
  { path: '/report-export', element: React.createElement(ReportExportPage) },
  { path: '/report-delivery', element: React.createElement(ReportDeliveryPage) },
  { path: '/publish', element: React.createElement(PublishPage) },
  { path: '/patient-report-portal', element: React.createElement(PatientReportPortalPage) },
  { path: '/ca-signature', element: React.createElement(CASignaturePage) },
  { path: '/blockchain-proof', element: React.createElement(BlockchainProofPage) },
  { path: '/appointment-management', element: React.createElement(AppointmentManagementPage) },
  { path: '/device-fault', element: React.createElement(DeviceFaultPage) },
  { path: '/ai-qc', element: React.createElement(AIQCPage) },
  { path: '/ai-structured-report', element: React.createElement(AIStructuredReportPage) },
  { path: '/ai-medical-device', element: React.createElement(AIMedicalDevicePage) },
  { path: '/regional-imaging', element: React.createElement(RegionalImagingPage) },
  { path: '/equipment-efficiency', element: React.createElement(EquipmentEfficiencyPage) },
  { path: '/user-management', element: React.createElement(UserManagementPage) },
  { path: '/patient-portal', element: React.createElement(PatientPortalPage) },
  { path: '/director-dashboard', element: React.createElement(DirectorDashboardPage) },
  { path: '/green-it', element: React.createElement(GreenITPage) },
  { path: '/research', element: React.createElement(ResearchPage) },
  { path: '/nuclear-stats', element: React.createElement(NuclearStatsPage) },
  { path: '/system/dicom-print', element: React.createElement(DicomPrintPage) },
  { path: '/term-synonym-graph', element: React.createElement(TermSynonymGraphPage) },
  { path: '/report-phrase-bank', element: React.createElement(ReportPhraseBankPage) },
  { path: '/report-kpi-dashboard', element: React.createElement(ReportKpiDashboardPage) },
  { path: '/doctor-workload', element: React.createElement(DoctorWorkloadPage) },
  { path: '/diagnosis-accuracy', element: React.createElement(DiagnosisAccuracyPage) },
  { path: '/report-timeliness', element: React.createElement(ReportTimelinessPage) },
  { path: '/report-search', element: React.createElement(ReportSearchPage) },
  { path: '/charge-items', element: React.createElement(ChargeItemPage) },
  { path: '/accounts-receivable', element: React.createElement(AccountsReceivablePage) },
  { path: '/revenue-analysis', element: React.createElement(RevenueAnalysisPage) },
  { path: '/cost-accounting', element: React.createElement(CostAccountingPage) },
  { path: '/financial-reports', element: React.createElement(FinancialReportsPage) },
  { path: '/business-continuity', element: React.createElement(BusinessContinuityPage) },
  { path: '/cloud-storage', element: React.createElement(CloudStorageDashboardPage) },
  { path: '/enterprise-search', element: React.createElement(EnterpriseSearchPage) },
  { path: '/multi-site', element: React.createElement(MultiSiteDashboardPage) },
  { path: '/vna-dashboard', element: React.createElement(VNADashboardPage) },
  { path: '/safety/adverse-events', element: React.createElement(AdverseEventPage) },
  { path: '/safety/cqi', element: React.createElement(CQIPage) },
  { path: '/safety/patient-safety-goals', element: React.createElement(PatientSafetyGoalsPage) },
  { path: '/safety/radiation-safety', element: React.createElement(RadiationSafetyPage) },
  { path: '/safety/rca-analysis', element: React.createElement(RCAAnalysisPage) },
  { path: '/safety/risk-management', element: React.createElement(RiskManagementPage) },
  { path: '/contrast/adverse-reactions', element: React.createElement(AdverseReactionPage) },
  { path: '/contrast/injection-workstation', element: React.createElement(ContrastInjectionWorkstationPage) },
  { path: '/contrast/inventory', element: React.createElement(ContrastInventoryPage) },
  { path: '/contrast/quality-compliance', element: React.createElement(ContrastQualityCompliancePage) },
  { path: '/cardiac/database', element: React.createElement(CvDatabasePage) },
  { path: '/cardiac/operations', element: React.createElement(CvOperationsPage) },
  { path: '/cardiac/qc', element: React.createElement(CvQcPage) },
  { path: '/ops/devices', element: React.createElement(DeviceOpsPage) },
  { path: '/ops/hr', element: React.createElement(HrOperationsPage) },
  { path: '/ops/dashboard', element: React.createElement(OpsDashboardPage) },
  { path: '/cds/management', element: React.createElement(CdsManagementPage) },
  { path: '/cds/statistics', element: React.createElement(CdsStatisticsPage) },
  { path: '/finance/department', element: React.createElement(DepartmentFinancePage) },
  { path: '/finance/patient', element: React.createElement(PatientFinancePage) },
  { path: '/mammo/operations', element: React.createElement(DepartmentOperationsPage) },
  { path: '/mammo/quality', element: React.createElement(QualityManagementPage) },
  { path: '/patient/self-service', element: React.createElement(SelfServicePortal) },
  { path: '/patient/service-management', element: React.createElement(ServiceManagement) },
  { path: '/education/patient-education', element: React.createElement(PatientEducationPage) },
  { path: '/hie/medical-alliance', element: React.createElement(MedicalAlliancePage) },
  { path: '/kiosk/check-in', element: React.createElement(KioskCheckIn) },
  { path: '/mobile/patient', element: React.createElement(PatientMobileApp) },
  { path: '/mobile/doctor', element: React.createElement(DoctorMobileWorkstation) },
  { path: '/mobile/nurse', element: React.createElement(NurseMobileWorkstation) },
  { path: '/mobile/tech', element: React.createElement(TechMobileWorkstation) },
  { path: '/quality/department', element: React.createElement(DepartmentQualityPage) },
  { path: '*', element: React.createElement(Navigate, { to: '/', replace: true }) },
]
