export type ExportFormat = 'pdf' | 'word' | 'html' | 'txt' | 'hl7' | 'dicom-sr' | 'csv';

export interface ExportOptions {
  format: ExportFormat;
  reportId: string;
  includeImages?: boolean;
  includeQR?: boolean;
  includeSignature?: boolean;
  includeWatermark?: boolean;
  paperSize?: 'A4' | 'A5' | 'B5';
  orientation?: 'portrait' | 'landscape';
}

export interface ExportResult {
  success: boolean;
  blob?: Blob;
  fileName?: string;
  error?: string;
}

export const FORMAT_MIME: Record<ExportFormat, string> = {
  pdf: 'application/pdf',
  word: 'application/msword',
  html: 'text/html',
  txt: 'text/plain',
  hl7: 'application/x-hl7',
  'dicom-sr': 'application/dicom+json',
  csv: 'text/csv',
};

export const FORMAT_EXT: Record<ExportFormat, string> = {
  pdf: 'pdf',
  word: 'doc',
  html: 'html',
  txt: 'txt',
  hl7: 'hl7',
  'dicom-sr': 'json',
  csv: 'csv',
};

function buildHtmlReport(opts: ExportOptions): string {
  const orientationCss = opts.orientation === 'landscape' ? '@page { size: landscape; }' : '';
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${opts.reportId}</title>
  <style>
    ${orientationCss}
    body { font-family: 'Noto Serif SC', serif; margin: 40px; color: #1e293b; line-height: 1.6; }
    h1 { font-size: 20px; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
    th { background: #f8fafc; font-weight: 600; }
    .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.08; font-size: 120px; pointer-events: none; z-index: 9999; }
    .footer { margin-top: 48px; text-align: center; color: #94a3b8; font-size: 12px; }
  </style>
</head>
<body>
  ${opts.includeWatermark ? '<div class="watermark">DRAFT</div>' : ''}
  <h1>放射诊断报告</h1>
  <p><strong>报告编号：</strong>${opts.reportId}</p>
  <table>
    <tr><th>姓名</th><td>—</td><th>性别</th><td>—</td></tr>
    <tr><th>检查项目</th><td colspan="3">—</td></tr>
    <tr><th>检查日期</th><td colspan="3">${new Date().toLocaleDateString('zh-CN')}</td></tr>
  </table>
  <h4>影像所见</h4>
  <p>—</p>
  <h4>诊断意见</h4>
  <p>—</p>
  ${opts.includeQR ? '<div style="margin-top:24px"><img src="data:image/svg+xml;base64,..." alt="QR" /></div>' : ''}
  <div class="footer">Generated by RIS v3.0.0 | ${new Date().toLocaleString('zh-CN')}</div>
</body>
</html>`;
}

function buildWordHtml(opts: ExportOptions): string {
  return `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <meta charset="UTF-8">
  <title>${opts.reportId}</title>
  <!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml><![endif]-->
  <style>
    body { font-family: 'Noto Serif SC', serif; margin: 2.54cm; color: #000; }
    h1 { font-size: 18pt; border-bottom: 2px solid #3b82f6; padding-bottom: 4pt; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1pt solid #999; padding: 4pt 8pt; text-align: left; }
    th { background: #f0f0f0; }
    .footer { margin-top: 36pt; text-align: center; font-size: 9pt; color: #666; }
  </style>
</head>
<body>
  <h1>放射诊断报告</h1>
  <p><strong>报告编号：</strong>${opts.reportId}</p>
  <table>
    <tr><th>姓名</th><td>—</td><th>性别</th><td>—</td></tr>
    <tr><th>检查项目</th><td colspan="3">—</td></tr>
    <tr><th>检查日期</th><td colspan="3">${new Date().toLocaleDateString('zh-CN')}</td></tr>
  </table>
  <h4>影像所见</h4>
  <p>—</p>
  <h4>诊断意见</h4>
  <p>—</p>
  <div class="footer">Generated by RIS v3.0.0</div>
</body>
</html>`;
}

async function handlePdfExport(opts: ExportOptions): Promise<ExportResult> {
  const html = buildHtmlReport(opts);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url);
  if (w) {
    w.addEventListener('afterprint', () => { w.close(); });
    w.print();
  }
  URL.revokeObjectURL(url);
  return { success: true, fileName: `${opts.reportId}.pdf` };
}

async function handleWordExport(opts: ExportOptions): Promise<ExportResult> {
  const html = buildWordHtml(opts);
  const blob = new Blob([html], { type: 'application/msword' });
  return { success: true, blob, fileName: `${opts.reportId}.doc` };
}

async function handleHtmlExport(opts: ExportOptions): Promise<ExportResult> {
  const html = buildHtmlReport(opts);
  const blob = new Blob([html], { type: 'text/html' });
  return { success: true, blob, fileName: `${opts.reportId}.html` };
}

async function handleTextExport(opts: ExportOptions): Promise<ExportResult> {
  const text = `放射诊断报告\n报告编号：${opts.reportId}\n检查日期：${new Date().toLocaleDateString('zh-CN')}\n\n影像所见\n—\n\n诊断意见\n—\n`;
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  return { success: true, blob, fileName: `${opts.reportId}.txt` };
}

async function handleHl7Export(opts: ExportOptions): Promise<ExportResult> {
  const hl7 = `MSH|^~\\&|RIS|HOSPITAL|||${new Date().toISOString()}||ORU^R01|${opts.reportId}|P|2.5.1\nPID|||12345||SMITH^JOHN||19700101|M\nOBR|1|${opts.reportId}||CT^ABDOMEN|||${new Date().toISOString()}\nOBX|1|TX||RADIOLOGY_REPORT|—|||F`;
  const blob = new Blob([hl7], { type: 'application/x-hl7' });
  return { success: true, blob, fileName: `${opts.reportId}.hl7` };
}

async function handleDicomSrExport(opts: ExportOptions): Promise<ExportResult> {
  const sr = {
    sopClassUID: '1.2.840.10008.5.1.4.1.1.88.22',
    studyInstanceUID: opts.reportId,
    patientName: '—',
    findings: '',
    conclusion: '',
    date: new Date().toISOString(),
  };
  const blob = new Blob([JSON.stringify(sr, null, 2)], { type: 'application/dicom+json' });
  return { success: true, blob, fileName: `${opts.reportId}.json` };
}

async function handleCsvExport(opts: ExportOptions): Promise<ExportResult> {
  const csv = '报告编号,姓名,性别,检查项目,检查日期,影像所见,诊断意见\n' +
    `${opts.reportId},—,—,—,${new Date().toLocaleDateString('zh-CN')},—,—\n`;
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  return { success: true, blob, fileName: `${opts.reportId}.csv` };
}

const HANDLERS: Record<ExportFormat, (opts: ExportOptions) => Promise<ExportResult>> = {
  pdf: handlePdfExport,
  word: handleWordExport,
  html: handleHtmlExport,
  txt: handleTextExport,
  hl7: handleHl7Export,
  'dicom-sr': handleDicomSrExport,
  csv: handleCsvExport,
};

export function exportReport(options: ExportOptions): Promise<ExportResult> {
  if (!options.reportId) {
    return Promise.resolve({ success: false, error: 'reportId is required' });
  }
  const handler = HANDLERS[options.format];
  if (!handler) {
    return Promise.resolve({ success: false, error: `Unsupported format: ${options.format}` });
  }
  return handler(options);
}

export async function exportToPdf(reportId: string, options?: Partial<ExportOptions>): Promise<ExportResult> {
  return exportReport({ format: 'pdf', reportId, ...options });
}

export async function exportToWord(reportId: string): Promise<ExportResult> {
  return exportReport({ format: 'word', reportId });
}

export async function exportToHtml(reportId: string): Promise<ExportResult> {
  return exportReport({ format: 'html', reportId });
}

export async function exportToText(reportId: string): Promise<ExportResult> {
  return exportReport({ format: 'txt', reportId });
}

export async function downloadExport(result: ExportResult): Promise<void> {
  if (!result.blob || !result.fileName) return;
  const url = URL.createObjectURL(result.blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = result.fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
