export { CriticalValueList, FilterBar } from './CriticalValueList'
export { DetailPanel } from './CriticalValueDetail'
export { ClosedLoopTracker, ClosedLoopTracker5Nodes } from './CriticalValueTimeline'
export { TransferToFollowUpModal, FollowUpTab, DocumentsTab } from './CriticalValueFollowUp'
export type { TransferToFollowUpModalProps } from './CriticalValueFollowUp'
export type { CriticalValue, TimelineEvent, DocumentItem, FollowUpRecord, ClosedLoopStage5 } from './types'
export { STATUS_CONFIG, SEVERITY_CONFIG, PRIMARY_COLOR, PRIMARY_LIGHT, PRIMARY_BG } from './types'
