// ============================================================
// G005 放射RIS系统 v2.0.0 - PDF 报告导出
// Phase R8 W7-F: jsPDF + html2canvas + 医院抬头 + 二维码
// ============================================================

// 注：jsPDF / html2canvas 加载较慢，按需引入
type JsPDF = any;

let jsPDFLib: typeof import('jspdf').jsPDF | null = null;
let qrcodeLib: typeof import('qrcode') | null = null;

async function loadJsPDF(): Promise<any> {
  if (jsPDFLib) return jsPDFLib;
  const mod = await import('jspdf');
  jsPDFLib = mod.jsPDF;
  return jsPDFLib;
}

async function loadQRCode(): Promise<any> {
  if (qrcodeLib) return qrcodeLib;
  const mod = await import('qrcode');
  qrcodeLib = mod;
  return qrcodeLib;
}

export interface PdfReportOptions {
  reportId: string;
  patientName: string;
  patientGender: string;
  patientAge: number;
  modality: string;
  bodyPart: string;
  studyDate: string;
  doctorName: string;
  findings: string;
  impression: string;
  recommendation?: string;
  hospitalName?: string;
  hospitalLogo?: string; // base64
  signatures?: Array<{ role: string; name: string; timestamp: string; imageData?: string }>;
  showQR?: boolean;
  watermark?: string;
  showStamp?: boolean;
}

export async function exportReportToPDF(opts: PdfReportOptions): Promise<Blob> {
  const JsPDFCtor = await loadJsPDF();
  const QRCode = await loadQRCode();
  const doc = new JsPDFCtor({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const W = 210, H = 297;
  const M = 15; // margin
  let y = M;

  // 医院抬头
  if (opts.hospitalName) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(opts.hospitalName, W / 2, y + 5, { align: 'center' });
    y += 12;
  }

  // 报告标题
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('RADIOLOGY REPORT', W / 2, y + 4, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(opts.modality + ' ' + opts.bodyPart, W / 2, y + 9, { align: 'center' });
  y += 14;
  doc.setLineWidth(0.5);
  doc.line(M, y, W - M, y);
  y += 6;

  // 患者信息
  doc.setFontSize(10);
  doc.text(`Patient: ${opts.patientName}    Gender: ${opts.patientGender}    Age: ${opts.patientAge}y`, M, y);
  y += 5;
  doc.text(`Study Date: ${opts.studyDate}    Modality: ${opts.modality}    Report ID: ${opts.reportId}`, M, y);
  y += 8;
  doc.setLineWidth(0.3);
  doc.line(M, y, W - M, y);
  y += 6;

  // Findings (所见)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('FINDINGS', M, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const findingsLines = doc.splitTextToSize(opts.findings || '(No findings)', W - 2 * M);
  doc.text(findingsLines, M, y);
  y += findingsLines.length * 4.5 + 4;

  // Impression (印象)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('IMPRESSION', M, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const impLines = doc.splitTextToSize(opts.impression || '(No impression)', W - 2 * M);
  doc.text(impLines, M, y);
  y += impLines.length * 4.5 + 4;

  // Recommendation (建议)
  if (opts.recommendation) {
    if (y > H - 60) { doc.addPage(); y = M; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('RECOMMENDATION', M, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const recLines = doc.splitTextToSize(opts.recommendation, W - 2 * M);
    doc.text(recLines, M, y);
    y += recLines.length * 4.5 + 4;
  }

  // 签名块
  if (y > H - 50) { doc.addPage(); y = M; }
  y += 8;
  doc.setLineWidth(0.3);
  doc.line(M, y, W - M, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  if (opts.signatures) {
    for (const sig of opts.signatures) {
      doc.text(`${sig.role}: ${sig.name}`, M, y);
      doc.text(`Time: ${new Date(sig.timestamp).toLocaleString()}`, W - M, y, { align: 'right' });
      y += 8;
    }
  } else {
    doc.text(`Reporting Doctor: ${opts.doctorName}`, M, y);
    doc.text(`Time: ${new Date().toLocaleString()}`, W - M, y, { align: 'right' });
    y += 8;
  }

  // 水印
  if (opts.watermark) {
    doc.setFontSize(40);
    doc.setTextColor(220, 220, 220);
    doc.text(opts.watermark, W / 2, H / 2, { align: 'center', angle: 45 });
    doc.setTextColor(0, 0, 0);
  }

  // QR 码
  if (opts.showQR !== false) {
    try {
      const qrData = await QRCode.toDataURL(
        JSON.stringify({ reportId: opts.reportId, ts: Date.now() }),
        { width: 100 }
      );
      doc.addImage(qrData, 'PNG', W - 35, H - 35, 25, 25);
    } catch (e) {
      // QR 加载失败忽略
    }
  }

  // 页脚
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by G005 RIS v2.0.0 | ${new Date().toISOString()}`, W / 2, H - 5, { align: 'center' });

  return doc.output('blob');
}

export async function downloadPdf(blob: Blob, filename: string): Promise<void> {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
