export const tokens = {
  color: {
    primary: {
      50: '--color-primary-50',
      100: '--color-primary-100',
      200: '--color-primary-200',
      300: '--color-primary-300',
      400: '--color-primary-400',
      500: '--color-primary-500',
      600: '--color-primary-600',
      700: '--color-primary-700',
      800: '--color-primary-800',
      900: '--color-primary-900',
      950: '--color-primary-950',
    },
    success: {
      50: '--color-success-50',
      100: '--color-success-100',
      200: '--color-success-200',
      300: '--color-success-300',
      400: '--color-success-400',
      500: '--color-success-500',
      600: '--color-success-600',
      700: '--color-success-700',
      800: '--color-success-800',
      900: '--color-success-900',
      950: '--color-success-950',
    },
    warning: {
      50: '--color-warning-50',
      100: '--color-warning-100',
      200: '--color-warning-200',
      300: '--color-warning-300',
      400: '--color-warning-400',
      500: '--color-warning-500',
      600: '--color-warning-600',
      700: '--color-warning-700',
      800: '--color-warning-800',
      900: '--color-warning-900',
      950: '--color-warning-950',
    },
    error: {
      50: '--color-error-50',
      100: '--color-error-100',
      200: '--color-error-200',
      300: '--color-error-300',
      400: '--color-error-400',
      500: '--color-error-500',
      600: '--color-error-600',
      700: '--color-error-700',
      800: '--color-error-800',
      900: '--color-error-900',
      950: '--color-error-950',
    },
    info: {
      50: '--color-info-50',
      100: '--color-info-100',
      200: '--color-info-200',
      300: '--color-info-300',
      400: '--color-info-400',
      500: '--color-info-500',
      600: '--color-info-600',
      700: '--color-info-700',
      800: '--color-info-800',
      900: '--color-info-900',
      950: '--color-info-950',
    },
    gray: {
      0: '--color-gray-0',
      50: '--color-gray-50',
      100: '--color-gray-100',
      200: '--color-gray-200',
      300: '--color-gray-300',
      400: '--color-gray-400',
      500: '--color-gray-500',
      600: '--color-gray-600',
      700: '--color-gray-700',
      800: '--color-gray-800',
      900: '--color-gray-900',
      1000: '--color-gray-1000',
    },
    semantic: {
      success: '--color-success',
      successBg: '--color-success-bg',
      successBorder: '--color-success-border',
      warning: '--color-warning',
      warningBg: '--color-warning-bg',
      warningBorder: '--color-warning-border',
      error: '--color-error',
      errorBg: '--color-error-bg',
      errorBorder: '--color-error-border',
      info: '--color-info',
      infoBg: '--color-info-bg',
      infoBorder: '--color-info-border',
      pending: '--color-pending',
      pendingBg: '--color-pending-bg',
      pendingBorder: '--color-pending-border',
    },
  },
  spacing: {
    0: '--space-0',
    px: '--space-px',
    0.5: '--space-0-5',
    1: '--space-1',
    1.5: '--space-1-5',
    2: '--space-2',
    2.5: '--space-2-5',
    3: '--space-3',
    4: '--space-4',
    5: '--space-5',
    6: '--space-6',
    8: '--space-8',
    10: '--space-10',
    12: '--space-12',
    16: '--space-16',
    20: '--space-20',
    24: '--space-24',
  },
  typography: {
    fontFamily: {
      sans: '--font-family-sans',
      mono: '--font-family-mono',
      medical: '--font-family-medical',
    },
    fontSize: {
      '2xs': '--font-size-2xs',
      xs: '--font-size-xs',
      sm: '--font-size-sm',
      base: '--font-size-base',
      md: '--font-size-md',
      lg: '--font-size-lg',
      xl: '--font-size-xl',
      '2xl': '--font-size-2xl',
      '3xl': '--font-size-3xl',
      '4xl': '--font-size-4xl',
      '5xl': '--font-size-5xl',
      '6xl': '--font-size-6xl',
    },
    fontWeight: {
      thin: '--font-weight-thin',
      extralight: '--font-weight-extralight',
      light: '--font-weight-light',
      normal: '--font-weight-normal',
      medium: '--font-weight-medium',
      semibold: '--font-weight-semibold',
      bold: '--font-weight-bold',
      extrabold: '--font-weight-extrabold',
    },
    lineHeight: {
      tight: '--line-height-tight',
      snug: '--line-height-snug',
      normal: '--line-height-normal',
      relaxed: '--line-height-relaxed',
      loose: '--line-height-loose',
      base: '--line-height-base',
    },
    letterSpacing: {
      tight: '--letter-spacing-tight',
      normal: '--letter-spacing-normal',
      wide: '--letter-spacing-wide',
      wider: '--letter-spacing-wider',
      widest: '--letter-spacing-widest',
    },
  },
  borderRadius: {
    none: '--radius-none',
    xs: '--radius-xs',
    sm: '--radius-sm',
    base: '--radius-base',
    md: '--radius-md',
    lg: '--radius-lg',
    xl: '--radius-xl',
    '2xl': '--radius-2xl',
    full: '--radius-full',
  },
  shadow: {
    xs: '--shadow-xs',
    sm: '--shadow-sm',
    base: '--shadow-base',
    md: '--shadow-md',
    lg: '--shadow-lg',
    xl: '--shadow-xl',
    '2xl': '--shadow-2xl',
    inner: '--shadow-inner',
    card: '--shadow-card',
    cardHover: '--shadow-card-hover',
    modal: '--shadow-modal',
    popover: '--shadow-popover',
    dropdown: '--shadow-dropdown',
    tooltip: '--shadow-tooltip',
    focus: '--shadow-focus',
    focusError: '--shadow-focus-error',
  },
  transition: {
    duration: {
      instant: '--duration-instant',
      fast: '--duration-fast',
      normal: '--duration-normal',
      slow: '--duration-slow',
      slower: '--duration-slower',
    },
    easing: {
      linear: '--ease-linear',
      in: '--ease-in',
      out: '--ease-out',
      inOut: '--ease-in-out',
      back: '--ease-back',
    },
    shorthand: {
      fast: '--transition-fast',
      normal: '--transition-normal',
      slow: '--transition-slow',
    },
  },
  zIndex: {
    base: '--z-base',
    dropdown: '--z-dropdown',
    sticky: '--z-sticky',
    fixed: '--z-fixed',
    modalBackdrop: '--z-modal-backdrop',
    modal: '--z-modal',
    popover: '--z-popover',
    tooltip: '--z-tooltip',
    toast: '--z-toast',
    max: '--z-max',
  },
  size: {
    icon: {
      xs: '--size-icon-xs',
      sm: '--size-icon-sm',
      md: '--size-icon-md',
      lg: '--size-icon-lg',
      xl: '--size-icon-xl',
      '2xl': '--size-icon-2xl',
    },
    control: {
      sm: '--size-control-sm',
      md: '--size-control-md',
      lg: '--size-control-lg',
      xl: '--size-control-xl',
    },
    tableRow: {
      sm: '--size-table-row-sm',
      md: '--size-table-row-md',
      lg: '--size-table-row-lg',
    },
    layout: {
      sidebar: '--size-sidebar',
      sidebarCollapsed: '--size-sidebar-collapsed',
      header: '--size-header',
      footer: '--size-footer',
      modalSm: '--size-modal-sm',
      modalMd: '--size-modal-md',
      modalLg: '--size-modal-lg',
      modalXl: '--size-modal-xl',
    },
  },
  semantic: {
    sidebar: {
      bg: '--sidebar-bg',
      fg: '--sidebar-fg',
      activeBg: '--sidebar-active-bg',
      activeFg: '--sidebar-active-fg',
      hoverBg: '--sidebar-hover-bg',
    },
    header: {
      bg: '--header-bg',
      fg: '--header-fg',
      border: '--header-border',
    },
    content: {
      bg: '--content-bg',
      fg: '--content-fg',
    },
    table: {
      headerBg: '--table-header-bg',
      headerFg: '--table-header-fg',
      rowHoverBg: '--table-row-hover-bg',
      rowCriticalBg: '--table-row-critical-bg',
    },
    form: {
      labelFg: '--form-label-fg',
      labelRequired: '--form-label-required',
      inputBg: '--form-input-bg',
      inputBorder: '--form-input-border',
      inputFocusBorder: '--form-input-focus-border',
      inputDisabledBg: '--form-input-disabled-bg',
    },
    skeleton: {
      bg: '--skeleton-bg',
      highlight: '--skeleton-highlight',
    },
    toast: {
      successBg: '--toast-success-bg',
      successBorder: '--toast-success-border',
      errorBg: '--toast-error-bg',
      errorBorder: '--toast-error-border',
      warningBg: '--toast-warning-bg',
      warningBorder: '--toast-warning-border',
      infoBg: '--toast-info-bg',
      infoBorder: '--toast-info-border',
    },
  },
} as const;

export type TokenValue = (typeof tokens)[keyof typeof tokens][keyof (typeof tokens)[keyof typeof tokens]];
