/**
 * G005 放射RIS系统 v3.0.6.0 - 打印模板设计器页面
 * Phase R7:可视化排版设计 + 列/边距/纸张配置
 */
import React, { useState } from 'react';
import { Save, Eye, FileText, Columns, Ruler, Type, RotateCcw } from 'lucide-react';
import type { PrintTemplate, PrintColumn } from '../types/export';

const emptyColumns = (): PrintColumn[] => [
  { key: 'patientName', label: '姓名', width: 20, align: 'left' },
  { key: 'reportId', label: '报告编号', width: 25, align: 'left' },
  { key: 'modality', label: '设备', width: 15, align: 'center' },
  { key: 'studyDate', label: '检查日期', width: 20, align: 'center' },
  { key: 'impression', label: '诊断', width: 20, align: 'left' },
];

export default function PrintTemplateDesignerPage() {
  const [template, setTemplate] = useState<PrintTemplate>({
    id: 'print-default',
    name: '默认打印模板',
    paperSize: 'A4',
    orientation: 'portrait',
    marginsMm: { top: 15, right: 10, bottom: 15, left: 10 },
    fontFamily: 'Noto Serif SC, serif',
    fontSize: 11,
    lineHeight: 1.5,
    columns: emptyColumns(),
    pageHeader: '放射诊断报告列表',
    pageFooter: 'Generated by G005 RIS',
    showPageNumber: true,
    showBranding: true,
    showWatermark: false,
  });

  const [saved, setSaved] = useState(false);

  const update = (patch: Partial<PrintTemplate>) => {
    setTemplate(prev => ({ ...prev, ...patch }));
    setSaved(false);
  };

  const updateColumn = (idx: number, patch: Partial<PrintColumn>) => {
    setTemplate(prev => ({
      ...prev,
      columns: prev.columns.map((c, i) => i === idx ? { ...c, ...patch } : c),
    }));
  };

  const addColumn = () => {
    setTemplate(prev => ({
      ...prev,
      columns: [...prev.columns, { key: `col${prev.columns.length + 1}`, label: `列${prev.columns.length + 1}`, width: 20, align: 'left' }],
    }));
  };

  const removeColumn = (idx: number) => {
    setTemplate(prev => ({
      ...prev,
      columns: prev.columns.filter((_, i) => i !== idx),
    }));
  };

  const handleSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div style={{ padding: 20, maxWidth: 1200, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div>
          <h1 style={{ fontSize: 22, color: '#1e293b', margin: 0, display: 'flex', alignItems: 'center', gap: 8 }}>
            <FileText size={20} color="#0891b2" /> 打印模板设计器
          </h1>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={handleSave} style={saveBtnStyle}><Save size={14} /> {saved ? '已保存' : '保存模板'}</button>
          <button onClick={() => update({ id: `print-${Date.now()}`, name: '新模板' })} style={resetBtnStyle}><RotateCcw size={14} /> 新建</button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '360px 1fr', gap: 16 }}>
        <div style={{ background: '#fff', borderRadius: 10, border: '1px solid #e2e8f0', padding: 16 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#1e293b', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 6 }}>
            <Ruler size={14} /> 页面设置
          </div>

          <div style={fieldGroup}>
            <label style={labelStyle}>模板名称</label>
            <input value={template.name} onChange={e => update({ name: e.target.value })} style={inputStyle} />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <div style={fieldGroup}>
              <label style={labelStyle}>纸张</label>
              <select value={template.paperSize} onChange={e => update({ paperSize: e.target.value as PrintTemplate['paperSize'] })} style={inputStyle}>
                <option value="A4">A4</option><option value="A5">A5</option>
                <option value="B5">B5</option><option value="Letter">Letter</option><option value="Legal">Legal</option>
              </select>
            </div>
            <div style={fieldGroup}>
              <label style={labelStyle}>方向</label>
              <select value={template.orientation} onChange={e => update({ orientation: e.target.value as PrintTemplate['orientation'] })} style={inputStyle}>
                <option value="portrait">纵向</option><option value="landscape">横向</option>
              </select>
            </div>
          </div>

          <div style={fieldGroup}>
            <label style={labelStyle}><Type size={11} /> 字体</label>
            <select value={template.fontFamily} onChange={e => update({ fontFamily: e.target.value })} style={inputStyle}>
              <option value="Noto Serif SC, serif">Noto Serif SC</option>
              <option value="SimSun, serif">宋体</option>
              <option value="Microsoft YaHei, sans-serif">微软雅黑</option>
            </select>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <div style={fieldGroup}>
              <label style={labelStyle}>字号</label>
              <input type="number" value={template.fontSize} onChange={e => update({ fontSize: +e.target.value })} style={inputStyle} min={8} max={24} />
            </div>
            <div style={fieldGroup}>
              <label style={labelStyle}>行高</label>
              <input type="number" value={template.lineHeight} onChange={e => update({ lineHeight: +e.target.value })} style={inputStyle} min={1} max={3} step={0.1} />
            </div>
          </div>

          <div style={fieldGroup}>
            <label style={labelStyle}>边距 (mm)</label>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 4 }}>
              {(['top', 'right', 'bottom', 'left'] as const).map(side => (
                <div key={side}>
                  <div style={{ fontSize: 9, color: '#94a3b8' }}>{side === 'top' ? '上' : side === 'bottom' ? '下' : side === 'left' ? '左' : '右'}</div>
                  <input type="number" value={template.marginsMm[side]} onChange={e => update({ marginsMm: { ...template.marginsMm, [side]: +e.target.value } })} style={inputStyle} min={0} max={50} />
                </div>
              ))}
            </div>
          </div>

          <div style={fieldGroup}>
            <label style={labelStyle}>页眉</label>
            <input value={template.pageHeader ?? ''} onChange={e => update({ pageHeader: e.target.value })} style={inputStyle} />
          </div>
          <div style={fieldGroup}>
            <label style={labelStyle}>页脚</label>
            <input value={template.pageFooter ?? ''} onChange={e => update({ pageFooter: e.target.value })} style={inputStyle} />
          </div>

          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <label style={{ fontSize: 11, color: '#475569', display: 'flex', alignItems: 'center', gap: 4 }}>
              <input type="checkbox" checked={template.showPageNumber} onChange={e => update({ showPageNumber: e.target.checked })} /> 页码
            </label>
            <label style={{ fontSize: 11, color: '#475569', display: 'flex', alignItems: 'center', gap: 4 }}>
              <input type="checkbox" checked={template.showBranding} onChange={e => update({ showBranding: e.target.checked })} /> 品牌
            </label>
            <label style={{ fontSize: 11, color: '#475569', display: 'flex', alignItems: 'center', gap: 4 }}>
              <input type="checkbox" checked={template.showWatermark} onChange={e => update({ showWatermark: e.target.checked })} /> 水印
            </label>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ background: '#fff', borderRadius: 10, border: '1px solid #e2e8f0', padding: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#1e293b', display: 'flex', alignItems: 'center', gap: 6 }}>
                <Columns size={14} /> 列定义 ({template.columns.length})
              </div>
              <button onClick={addColumn} style={addBtnStyle}><Columns size={12} /> 添加列</button>
            </div>

            {template.columns.map((col, idx) => (
              <div key={idx} style={{ display: 'flex', gap: 6, alignItems: 'center', marginBottom: 6, padding: 8, background: '#f8fafc', borderRadius: 6 }}>
                <span style={{ fontSize: 10, color: '#94a3b8', width: 20 }}>{idx + 1}</span>
                <input value={col.key} onChange={e => updateColumn(idx, { key: e.target.value })} style={{ ...inputStyle, width: 120 }} placeholder="字段名" />
                <input value={col.label} onChange={e => updateColumn(idx, { label: e.target.value })} style={{ ...inputStyle, width: 100 }} placeholder="显示名" />
                <input type="number" value={col.width} onChange={e => updateColumn(idx, { width: +e.target.value })} style={{ ...inputStyle, width: 60 }} min={5} max={80} />
                <select value={col.align ?? 'left'} onChange={e => updateColumn(idx, { align: e.target.value as PrintColumn['align'] })} style={{ ...inputStyle, width: 70 }}>
                  <option value="left">左</option><option value="center">中</option><option value="right">右</option>
                </select>
                <button onClick={() => removeColumn(idx)} style={{ background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', fontSize: 14 }}>×</button>
              </div>
            ))}
          </div>

          <div style={{ background: '#fff', borderRadius: 10, border: '1px solid #e2e8f0', padding: 16 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
              <Eye size={14} color="#0891b2" />
              <span style={{ fontSize: 13, fontWeight: 700, color: '#1e293b' }}>预览</span>
              <span style={{ fontSize: 10, color: '#94a3b8' }}>{template.paperSize} · {template.orientation === 'portrait' ? '纵向' : '横向'}</span>
            </div>
            <div style={{ background: '#f8fafc', borderRadius: 6, border: '1px solid #e2e8f0', padding: 12, minHeight: 200 }}>
              {template.pageHeader && (
                <div style={{ fontSize: template.fontSize + 2, fontWeight: 700, color: '#1e293b', borderBottom: '2px solid #e2e8f0', paddingBottom: 8, marginBottom: 8 }}>
                  {template.pageHeader}
                </div>
              )}
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: template.fontSize - 1 }}>
                <thead>
                  <tr style={{ background: '#f1f5f9' }}>
                    {template.columns.map(col => (
                      <th key={col.key} style={{ padding: '4px 6px', textAlign: col.align ?? 'left', borderBottom: '1px solid #e2e8f0', fontSize: template.fontSize - 1, fontWeight: 600, color: '#475569' }}>
                        {col.label}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {template.columns.map(col => (
                      <td key={col.key} style={{ padding: '4px 6px', textAlign: col.align ?? 'left', borderBottom: '1px solid #f1f5f9', fontSize: template.fontSize - 1, color: '#94a3b8' }}>
                        —
                      </td>
                    ))}
                  </tr>
                </tbody>
              </table>
              {template.pageFooter && (
                <div style={{ marginTop: 16, fontSize: template.fontSize - 2, color: '#94a3b8', textAlign: 'center', borderTop: '1px solid #e2e8f0', paddingTop: 8 }}>
                  {template.pageFooter}
                  {template.showPageNumber && <span> · 第 1 页</span>}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const fieldGroup: React.CSSProperties = { marginBottom: 10 };
const labelStyle: React.CSSProperties = { fontSize: 11, color: '#475569', display: 'block', marginBottom: 3, fontWeight: 500 };
const inputStyle: React.CSSProperties = {
  width: '100%', padding: '6px 10px', border: '1px solid #cbd5e1', borderRadius: 4, fontSize: 12, outline: 'none',
};
const saveBtnStyle: React.CSSProperties = {
  padding: '8px 16px', border: 'none', borderRadius: 6, background: '#0891b2', color: '#fff', fontSize: 12, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
};
const resetBtnStyle: React.CSSProperties = {
  padding: '8px 16px', border: '1px solid #cbd5e1', borderRadius: 6, background: '#fff', color: '#475569', fontSize: 12, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
};
const addBtnStyle: React.CSSProperties = {
  padding: '4px 10px', border: '1px solid #0891b2', borderRadius: 4, background: '#ecfeff', color: '#0891b2', fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
};
