/**
 * G005 放射RIS系统 v3.0.6.0 - 站点品牌引擎
 * Phase R7:导出报告统一品牌(Logo/页脚/主色)
 */
import type { BrandingConfig } from '../../types/export';

const DEFAULT_BRANDING: BrandingConfig = {
  siteName: 'G005 放射RIS系统',
  footerText: 'Generated by G005 RIS v3.0.6 · 临床参考',
  primaryColor: '#1e40af',
  secondaryColor: '#dc2626',
  fontFamily: 'Noto Serif SC, serif',
  showWatermark: false,
  showQrCode: true,
  showSignature: true,
};

const STORAGE_KEY = 'g005:export:branding';

export class BrandingEngine {
  private config: BrandingConfig;
  private readonly listeners = new Set<(c: BrandingConfig) => void>();

  constructor(initial?: Partial<BrandingConfig>) {
    this.config = { ...DEFAULT_BRANDING, ...(initial ?? {}) };
  }

  getConfig(): BrandingConfig {
    return { ...this.config };
  }

  update(patch: Partial<BrandingConfig>): BrandingConfig {
    this.config = { ...this.config, ...patch };
    this.persist();
    this.emit();
    return this.getConfig();
  }

  reset(): BrandingConfig {
    this.config = { ...DEFAULT_BRANDING };
    this.persist();
    this.emit();
    return this.getConfig();
  }

  subscribe(fn: (c: BrandingConfig) => void): () => void {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  }

  buildCssVariables(): string {
    const c = this.config;
    return [
      `--brand-primary:${c.primaryColor};`,
      `--brand-secondary:${c.secondaryColor};`,
      `--brand-font:${c.fontFamily};`,
      `--brand-site-name:"${c.siteName}";`,
    ].join('');
  }

  buildHtmlHeader(): string {
    const c = this.config;
    const logo = c.logoDataUrl
      ? `<img src="${c.logoDataUrl}" alt="logo" style="height:36px;vertical-align:middle;margin-right:8px;" />`
      : '';
    return `<div style="display:flex;align-items:center;border-bottom:2px solid ${c.primaryColor};padding-bottom:8px;margin-bottom:12px;">
      ${logo}
      <span style="font-family:${c.fontFamily};font-size:18px;font-weight:700;color:${c.primaryColor};">${escapeHtml(c.siteName)}</span>
    </div>`;
  }

  buildHtmlFooter(): string {
    const c = this.config;
    const contact = [c.contactEmail, c.contactPhone].filter(Boolean).join(' · ');
    return `<div style="margin-top:24px;padding-top:8px;border-top:1px solid #e2e8f0;text-align:center;color:#94a3b8;font-size:11px;font-family:${c.fontFamily};">
      ${escapeHtml(c.footerText)}${contact ? ` · ${escapeHtml(contact)}` : ''}
    </div>`;
  }

  applyTo(html: string): string {
    const variables = this.buildCssVariables();
    const header = this.buildHtmlHeader();
    const footer = this.buildHtmlFooter();
    let out = html;
    if (out.includes('<head>')) {
      out = out.replace('<head>', `<head><style>:root{${variables}}</style>`);
    }
    if (out.includes('<body>')) {
      out = out.replace('<body>', `<body>${header}`);
    }
    if (/<\/body>/.test(out)) {
      out = out.replace(/<\/body>/, `${footer}</body>`);
    } else {
      out += footer;
    }
    return out;
  }

  toJSON(): BrandingConfig {
    return this.getConfig();
  }

  private persist(): void {
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(this.config));
      }
    } catch {
      // ignore
    }
  }

  private emit(): void {
    const snapshot = this.getConfig();
    this.listeners.forEach(fn => {
      try {
        fn(snapshot);
      } catch {
        // ignore listener errors
      }
    });
  }
}

let singleton: BrandingEngine | null = null;

export function getBrandingEngine(): BrandingEngine {
  if (!singleton) {
    let initial: Partial<BrandingConfig> | undefined;
    try {
      if (typeof localStorage !== 'undefined') {
        const raw = localStorage.getItem(STORAGE_KEY);
        if (raw) initial = JSON.parse(raw) as Partial<BrandingConfig>;
      }
    } catch {
      initial = undefined;
    }
    singleton = new BrandingEngine(initial);
  }
  return singleton;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export { DEFAULT_BRANDING };